import { AuthProvider } from "@/context/auth.context";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen">
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="px-8 py-4">{children}</main>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
